SportPro/Models/ErrorViewModel.cs
namespace SportPro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SportPro/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportPro.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportPro/Controllers/HomeController.cs
//Member Gowthaman Kangatharan - 101247677

using Microsoft.AspNetCore.Mvc;
using SportPro.Models;
using System.Diagnostics;

namespace SportPro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Products()
        {
            return View();
        }

        public IActionResult About() 
        {
            return View();
        }
        public IActionResult Technicians()
        {
            return View();
        }

        public IActionResult Customer() 
        {
            return View();
        }

        public IActionResult Incident()
        {
            return View();
        }
        public IActionResult Registration()
        {
            return View();
        }

        public IActionResult AddProducts() 
        {
            return View();
        }

        public IActionResult AddTechnicians() 
        {
            return View();
        }

        public IActionResult AddCustomers() 
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SportPro/Controllers/IncidentController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportPro.Controllers
{
    public class IncidentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportPro/Controllers/ProductController.cs
//Member Gowthaman Kangatharan - 101247677

using Microsoft.AspNetCore.Mvc;
using SportPro.Models;
using System.Diagnostics;

namespace SportPro.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportPro/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportPro.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportPro/Controllers/TechnicianController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportPro.Controllers
{
    public class TechnicianController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportPro/Views/Home/About.cshtml
@*Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "About Page";
}

<div class="text-center">
    <h1 class="display-4">About Page</h1>
    <p>Hello World</a>.</p>
</div>

SportPro/Views/Home/AddCustomers.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Add Customer Page";
}

<div>
    <h2>Add Customer</h2>
    <label>First Name</label>
    <br />
    <input type = "text" name = "Fname" id = "Fname" required/>
    <br />
    <label>Last Name</label>
    <br />
    <input type = "text" name = "Lname" id = "Lname" required/>
    <br />
    <label>Address</label>
    <br />
    <input type = "text" name = "Address" id = "Adress" required/>
    <br />
    <label>City</label>
    <br />
    <input type = "text" name = "City" id = "City" required/>
    <br />
    <label>State</label>
    <br />
    <input type = "text" name = "State" id = "State" required/>
    <br />
    <label>Countty</label>
    <br />
    <input type = "text" name = "Country" id = "Country" required/>
    <br />
    <label>Email</label>
    <br />
    <input type = "text" name = "Email" id = "Email" required/>
    <br />
    <label>Phone</label>
    <br />
    <input type = "text" name = "Phone" id = "Phone" required/>
    <br />
    <a class = "btn btn-primary" asp-controller="Home" asp-action="SaveCustomer" type="submit" name="saveBtn">Save </a>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="Customer" type="submit" name="calBtn">Cancel</a>
</div>


SportPro/Views/Home/AddIncident.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Edit Incident Page";
}

<div>
    <h2>Edit Incident</h2>
    <label>Customer</label>
    <br />
    <input type = "text" name = "customer" id = "CustomerId" required/>
    <br />
    <label>Product</label>
    <br />
    <input type = "text" name = "product" id = "productId" required/>
    <br />
    <label>Title</label>
    <br />
    <input type = "text" name = "title" id = "titleID" required/>
    <br />
    <label>Description</label>
    <br />
    <input type = "text" name = "description" id = "descriptionId" required/>
    <br />
    <label>Technician</label>
    <br />
    <input type = "text" name = "technicianIncident" id = "technicianIncident_Id" required/>
    <br />
    <label>Date Opened</label>
    <br />
    <input type = "text" name = "dateOp" id = "dateOp_Id" required/>
    <br />
    <label>Date Opened</label>
    <br />
    <input type = "text" name = "dateCl" id = "dateCl_Id" required/>
    <br />
    <a class = "btn btn-primary" asp-controller="Home" asp-action="SaveProduct" type="submit" name="saveBtn">Save </a>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="Products" type="submit" name="calBtn">Cancel</a>
</div>

SportPro/Views/Home/AddProducts.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Add Product Page";
}

<div>
    <h2>Product Manger</h2>
    <label>Code</label>
    <br />
    <input type = "text" name = "Code" id = "Code" required/>
    <br />
    <label>Name</label>
    <br />
    <input type = "text" name = "Name" id = "Name" required/>
    <br />
    <label>Yearly Price</label>
    <br />
    <input type = "text" name = "yrlyPrice" id = "yrlyPrice" required/>
    <br />
    <label>Released Date</label>
    <br />
    <input type = "text" name = "reDate" id = "reDate" required/>
    <br />
    <a class = "btn btn-primary" asp-controller="Home" asp-action="SaveProduct" type="submit" name="saveBtn">Save </a>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="Products" type="submit" name="calBtn">Cancel</a>
</div>

SportPro/Views/Home/AddTechnicians.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Add Technicians Page";
}

<div>
    <h2>Add Technicians</h2>
    <label>Name</label>
    <br />
    <input type = "text" name = "Name" id = "Name" required/>
    <br />
    <label>Email</label>
    <br />
    <input type = "text" name = "Email" id = "Email" required/>
    <br />
    <label>Phone</label>
    <br />
    <input type = "text" name = "Phone" id = "Phone" required/>
    <br />
    <a class = "btn btn-primary" asp-controller="Home" asp-action="SaveTechnicians" type="submit" name="saveBtn">Save </a>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="Technicians" type="submit" name="calBtn">Cancel</a>
</div>

SportPro/Views/Home/Customer.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Customers Manger";
}
<div>
    <h2>Customers Manger</h2>
    <table class="table table-bordered w-50">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>City</th>
            <th></th>
            <th></th>
        </tr>
    </table>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="AddCustomers" type="submit" name="AddCustomerBtn">Add Customer</a>
</div>

SportPro/Views/Home/EditProducts.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Manage Product Page";
}

<div>
    <h2>Product Manger</h2>
    <table class="table table-bordered table-hover w-50">
        <tr>
            <th>
                <a>Code</a>
            </th>
        </tr>
        <tr>
            <th>
                <a>Name</a>
            </th>
        </tr>
    </table>
</div>

SportPro/Views/Home/Incident.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h2>Incident Manger</h2>
    <table class="table table-bordered w-50">
        <tr>
            <th>Title</th>
            <th>Customer</th>
            <th>Product</th>
            <th>Date Opened</th>
            <th></th>
            <th></th>
        </tr>
    </table>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="AddIncident" type="submit" name="AddIncidentBtn">Add Incidents</a>
</div>

SportPro/Views/Home/Index.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h2>Sports Pro Technical Support</h2>
    <p>Sports management software For the sports enthusiast</a></p>
</div>
<div>
    <h2>Admin</h2>
    <table class="table table-bordered table-hover w-50">
        <tr>
            <td>
                <a class="nav-link" asp-controller="Products" asp-action="Products">Manage Products</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="nav-link" asp-controller="Technician" asp-action="Technician">Manage Technicians</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="nav-link" asp-controller="Customer" asp-action="Customer">Manage Customers</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="nav-link" asp-controller="Incident" asp-action="Incident">Manage Incidents</a>
            </td>
        </tr>
        <tr>
            <td>
                <a class="nav-link" asp-controller="Registration" asp-action="Registration">Manage Registrations</a>
            </td>
        </tr>
    </table>
</div>
<div>
    <h2>Technicians</h2>
    <table class="table table-bordered table-hover w-50">
        <tr>
            <td>
                <a class="nav-link" asp-controller="Products" asp-action="Index">Update Incidents</a>
            </td>
        </tr>
    </table>
</div>

SportPro/Views/Home/Products.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Product Page";
}

<div>
    <h2>Product Manger</h2>
    <table class="table table-bordered w-50">
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Price</th>
            <th>Release Date</th>
            <th></th>
            <th></th>
        </tr>
    </table>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="AddProducts" type="submit" name="AddBtn">Add Product</a>
</div>

SportPro/Views/Home/Registration.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Registration Page</h1>
    <p>Hello World</a>.</p>
</div>


SportPro/Views/Home/Technicians.cshtml
@*//Member Gowthaman Kangatharan - 101247677*@
@{
    ViewData["Title"] = "Technicians Page";
}
<div>
    <h2>Technicians Manger</h2>
    <table class="table table-bordered w-50">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th></th>
            <th></th>
        </tr>
    </table>
    <a class = "btn btn-primary" asp-controller="Home" asp-action="AddTechnicians" type="submit" name="AddTechniciansBtn">Add Technicians</a>
</div>

SportPro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportPro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportPro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SportsPro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Technicians">Technicians</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Customer">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Incident">Incidents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Registration">Registrations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SportPro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>